### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by agoniaprivat** [pl3xgaming/Pl3xMap2#1]
https://pastebin.com/2Skm3PZF

Shouts out errors, over GB long log file.
This is the errors. No startup errors coming, only when players join.

My map is like 80% generated already, but stopped after a while.
http://karta.agoniamc.eu/

**Comment by 12emin34** [comment]
This repo is made for the upcoming rewrite of the plugin, open the issue here: https://github.com/pl3xgaming/Pl3xMap
